##
## Main configuration file for the Perplex documentation
##

# The domain of the site
baseURL: http://perplex.desider.at
title: Perplex Theme
DefaultLanguageCode: en-us
DefaultContentLanguage: en
metaDataFormat: yaml
pluralizeListTitles: false
enableEmoji: true
enableGitInfo: true

timeout: 500000 # Milliseconds

taxonomies:
  tag: tags
  category: categories
  series: series

ignoreErrors:
  - error-missing-instagram-accesstoken
  - error-remote-getjson

caches:
  assets:
    dir: :resourceDir/_gen
    maxAge: -1
  getcsv:
    dir: :cacheDir/:project
    maxAge: -1
  getjson:
    dir: :cacheDir/:project
    maxAge: -1
  getresource:
    dir: :resourceDir/:project
    maxAge: -1
  images:
    dir: :resourceDir/_gen
    maxAge: -1
  modules:
    dir: :cacheDir/modules
    maxAge: -1