#
# Theme-specific parameters
#

# Site wide favicon for browser and OS display
favicon:
  svg: icon/favicon.svg
  png: icon/favicon.png

sourceURL: https://github.com/bowman2001/perplexdoc
sourceEditTree: edit/main/content
