#
# Additional parameters
#

description: Perplex is a typographic theme with advanced layout capabilities. You can publish technical content in a full documentation, a blog or longer articles.
embedFull: false
svg: inline

# Site wide favicon for browser and OS display
favicon:
  svg: icon/favicon.svg
  png: icon/favicon.png

sourceURL: https://github.com/bowman2001/perplexdoc
sourceEditTree: edit/main/content

imaging:
  sizestep: 100
  fallback_width: 1920
