#
# Theme-specific parameters
#

logo: logo/Perplex_white.svg

# Site-wide default image. It gets overridden by
# the page- or section-specific front-matter parameter.
featImg: logo/Perplex.svg

# Site wide favicon for browser and OS display
favicon:
  svg: icon/favicon.svg
  png: icon/favicon.png

sourceURL: https://github.com/bowman2001/perplexdoc
sourceEditTree: edit/main/content
