#
# Additional parameters
#

description: Perplex is a typographic theme with advanced layout capabilities. You can publish technical content in a documentation, a blog, as news or long articles.

postcss: false

# Site wide favicon for browser and OS display
favicon:
  svg: favicon/favicon.svg
  png: favicon/favicon.png

modOpenIn:
  name: VSCodium
  protocol: vscodium
# fathomSiteID: ABCDEFG

render_hooks:
  link:
    errorLevel: warning
  fragments:
    errorLevel: ignore
