[build]
publish = "public"
command = "hugo --gc --minify --environment netlify"

[build.environment]
HUGO_VERSION = "0.111.2"
# GO_VERSION = "1.18"
HUGO_ENABLEGITINFO = "true"

[context.develop]
command = "hugo --gc --minify --environment development"

[[redirects]]
from = "/*"
to = "/404/"
status = 404