[build]
publish = "public"
command = "hugo --gc --minify --environment netlify && npx pagefind --source 'public'"

[build.environment]
HUGO_VERSION = "0.113.0"
GO_VERSION = "1.20"
HUGO_ENABLEGITINFO = "true"

[context.develop]
command = "hugo --gc --minify --environment development"

[[redirects]]
from = "/*"
to = "/404/"
status = 404