[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.97.1"
GO_VERSION = "1.18"
HUGO_ENABLEGITINFO = "true"

[context.develop]
command = "hugo --gc --minify --environment development"
