[build]
publish = "public"
command = "hugo --gc --minify && npx pagefind"

[build.environment]
HUGO_VERSION = "0.123.7"
GO_VERSION = "1.21.6"
HUGO_ENABLEGITINFO = "true"

[context.develop]
command = "hugo --gc --minify --environment development"

[[redirects]]
from = "/*"
to = "/404/"
status = 404